name: V's Blog
description: V's Tips and Tricks for Developers
markdown: redcarpet
url: http://vverma.net
highlighter: pygments
exclude:
    - fabfile.py
    - Gemfile
    - Gemfile.lock
permalink: :title.html
